name: Build and Push OpenAS2 Image to Docker Hub

# Déclencheurs : Ce pipeline s'exécutera automatiquement...
on:
  # ...à chaque fois que vous poussez du code sur la branche 'master' de votre fork.
  push:
    branches: [ "master" ]
  # ...ou si vous voulez le lancer manuellement depuis l'interface GitHub.
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mon-openas2-perso

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
